# Generated by Django 5.0.7 on 2024-07-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcategory",
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
